//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from AttackSkill.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IAttackSkillListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class AttackSkillBaseListener : IAttackSkillListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.root"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRoot([NotNull] AttackSkillParser.RootContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.root"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRoot([NotNull] AttackSkillParser.RootContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.numEntries"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumEntries([NotNull] AttackSkillParser.NumEntriesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.numEntries"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumEntries([NotNull] AttackSkillParser.NumEntriesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.create"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCreate([NotNull] AttackSkillParser.CreateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.create"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCreate([NotNull] AttackSkillParser.CreateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.skillProperty"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSkillProperty([NotNull] AttackSkillParser.SkillPropertyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.skillProperty"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSkillProperty([NotNull] AttackSkillParser.SkillPropertyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.animBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnimBlock([NotNull] AttackSkillParser.AnimBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.animBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnimBlock([NotNull] AttackSkillParser.AnimBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.fxBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFxBlock([NotNull] AttackSkillParser.FxBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.fxBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFxBlock([NotNull] AttackSkillParser.FxBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.effectBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEffectBlock([NotNull] AttackSkillParser.EffectBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.effectBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEffectBlock([NotNull] AttackSkillParser.EffectBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.statusBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatusBlock([NotNull] AttackSkillParser.StatusBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.statusBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatusBlock([NotNull] AttackSkillParser.StatusBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.projectileBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProjectileBlock([NotNull] AttackSkillParser.ProjectileBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.projectileBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProjectileBlock([NotNull] AttackSkillParser.ProjectileBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.createDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCreateDef([NotNull] AttackSkillParser.CreateDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.createDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCreateDef([NotNull] AttackSkillParser.CreateDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.useClass"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUseClass([NotNull] AttackSkillParser.UseClassContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.useClass"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUseClass([NotNull] AttackSkillParser.UseClassContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.displayNameId"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDisplayNameId([NotNull] AttackSkillParser.DisplayNameIdContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.displayNameId"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDisplayNameId([NotNull] AttackSkillParser.DisplayNameIdContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.descriptionId"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDescriptionId([NotNull] AttackSkillParser.DescriptionIdContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.descriptionId"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDescriptionId([NotNull] AttackSkillParser.DescriptionIdContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.level"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLevel([NotNull] AttackSkillParser.LevelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.level"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLevel([NotNull] AttackSkillParser.LevelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.jobPointCost"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJobPointCost([NotNull] AttackSkillParser.JobPointCostContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.jobPointCost"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJobPointCost([NotNull] AttackSkillParser.JobPointCostContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.prereq"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrereq([NotNull] AttackSkillParser.PrereqContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.prereq"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrereq([NotNull] AttackSkillParser.PrereqContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttribute([NotNull] AttackSkillParser.AttributeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttribute([NotNull] AttackSkillParser.AttributeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.costs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCosts([NotNull] AttackSkillParser.CostsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.costs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCosts([NotNull] AttackSkillParser.CostsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.shiftData"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShiftData([NotNull] AttackSkillParser.ShiftDataContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.shiftData"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShiftData([NotNull] AttackSkillParser.ShiftDataContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.affCost"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAffCost([NotNull] AttackSkillParser.AffCostContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.affCost"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAffCost([NotNull] AttackSkillParser.AffCostContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.effect"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEffect([NotNull] AttackSkillParser.EffectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.effect"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEffect([NotNull] AttackSkillParser.EffectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.effectFX"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEffectFX([NotNull] AttackSkillParser.EffectFXContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.effectFX"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEffectFX([NotNull] AttackSkillParser.EffectFXContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.splitEffect"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSplitEffect([NotNull] AttackSkillParser.SplitEffectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.splitEffect"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSplitEffect([NotNull] AttackSkillParser.SplitEffectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.splitEffectCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSplitEffectCondition([NotNull] AttackSkillParser.SplitEffectConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.splitEffectCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSplitEffectCondition([NotNull] AttackSkillParser.SplitEffectConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.effectSkillCond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEffectSkillCond([NotNull] AttackSkillParser.EffectSkillCondContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.effectSkillCond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEffectSkillCond([NotNull] AttackSkillParser.EffectSkillCondContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.combatMods"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCombatMods([NotNull] AttackSkillParser.CombatModsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.combatMods"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCombatMods([NotNull] AttackSkillParser.CombatModsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.moveToAttackMod"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMoveToAttackMod([NotNull] AttackSkillParser.MoveToAttackModContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.moveToAttackMod"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMoveToAttackMod([NotNull] AttackSkillParser.MoveToAttackModContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.affinity"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAffinity([NotNull] AttackSkillParser.AffinityContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.affinity"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAffinity([NotNull] AttackSkillParser.AffinityContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.range"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRange([NotNull] AttackSkillParser.RangeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.range"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRange([NotNull] AttackSkillParser.RangeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.excludeRange"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExcludeRange([NotNull] AttackSkillParser.ExcludeRangeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.excludeRange"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExcludeRange([NotNull] AttackSkillParser.ExcludeRangeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.meter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMeter([NotNull] AttackSkillParser.MeterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.meter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMeter([NotNull] AttackSkillParser.MeterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.anim"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnim([NotNull] AttackSkillParser.AnimContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.anim"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnim([NotNull] AttackSkillParser.AnimContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.loopAnim"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoopAnim([NotNull] AttackSkillParser.LoopAnimContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.loopAnim"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoopAnim([NotNull] AttackSkillParser.LoopAnimContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.moveAnim"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMoveAnim([NotNull] AttackSkillParser.MoveAnimContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.moveAnim"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMoveAnim([NotNull] AttackSkillParser.MoveAnimContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.defendAnim"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefendAnim([NotNull] AttackSkillParser.DefendAnimContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.defendAnim"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefendAnim([NotNull] AttackSkillParser.DefendAnimContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.lowAnim"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLowAnim([NotNull] AttackSkillParser.LowAnimContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.lowAnim"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLowAnim([NotNull] AttackSkillParser.LowAnimContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.chargeAnim"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChargeAnim([NotNull] AttackSkillParser.ChargeAnimContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.chargeAnim"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChargeAnim([NotNull] AttackSkillParser.ChargeAnimContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.animTime"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnimTime([NotNull] AttackSkillParser.AnimTimeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.animTime"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnimTime([NotNull] AttackSkillParser.AnimTimeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.animStartFrame"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnimStartFrame([NotNull] AttackSkillParser.AnimStartFrameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.animStartFrame"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnimStartFrame([NotNull] AttackSkillParser.AnimStartFrameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.fx"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFx([NotNull] AttackSkillParser.FxContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.fx"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFx([NotNull] AttackSkillParser.FxContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.fxSwing"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFxSwing([NotNull] AttackSkillParser.FxSwingContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.fxSwing"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFxSwing([NotNull] AttackSkillParser.FxSwingContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.fxCTAG"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFxCTAG([NotNull] AttackSkillParser.FxCTAGContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.fxCTAG"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFxCTAG([NotNull] AttackSkillParser.FxCTAGContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.fxProjectile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFxProjectile([NotNull] AttackSkillParser.FxProjectileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.fxProjectile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFxProjectile([NotNull] AttackSkillParser.FxProjectileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.projectile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProjectile([NotNull] AttackSkillParser.ProjectileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.projectile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProjectile([NotNull] AttackSkillParser.ProjectileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.projectileSequence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProjectileSequence([NotNull] AttackSkillParser.ProjectileSequenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.projectileSequence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProjectileSequence([NotNull] AttackSkillParser.ProjectileSequenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.projectileRotation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProjectileRotation([NotNull] AttackSkillParser.ProjectileRotationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.projectileRotation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProjectileRotation([NotNull] AttackSkillParser.ProjectileRotationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.projectileAttr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProjectileAttr([NotNull] AttackSkillParser.ProjectileAttrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.projectileAttr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProjectileAttr([NotNull] AttackSkillParser.ProjectileAttrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.status"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatus([NotNull] AttackSkillParser.StatusContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.status"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatus([NotNull] AttackSkillParser.StatusContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.statusDuration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatusDuration([NotNull] AttackSkillParser.StatusDurationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.statusDuration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatusDuration([NotNull] AttackSkillParser.StatusDurationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.statusTarget"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatusTarget([NotNull] AttackSkillParser.StatusTargetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.statusTarget"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatusTarget([NotNull] AttackSkillParser.StatusTargetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.statusSituationAffinityCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatusSituationAffinityCondition([NotNull] AttackSkillParser.StatusSituationAffinityConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.statusSituationAffinityCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatusSituationAffinityCondition([NotNull] AttackSkillParser.StatusSituationAffinityConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.statusChance"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatusChance([NotNull] AttackSkillParser.StatusChanceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.statusChance"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatusChance([NotNull] AttackSkillParser.StatusChanceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.effectStatusCond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEffectStatusCond([NotNull] AttackSkillParser.EffectStatusCondContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.effectStatusCond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEffectStatusCond([NotNull] AttackSkillParser.EffectStatusCondContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.statusInterval"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatusInterval([NotNull] AttackSkillParser.StatusIntervalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.statusInterval"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatusInterval([NotNull] AttackSkillParser.StatusIntervalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.statusCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatusCondition([NotNull] AttackSkillParser.StatusConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.statusCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatusCondition([NotNull] AttackSkillParser.StatusConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.skillStatusSituationUnitCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSkillStatusSituationUnitCondition([NotNull] AttackSkillParser.SkillStatusSituationUnitConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.skillStatusSituationUnitCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSkillStatusSituationUnitCondition([NotNull] AttackSkillParser.SkillStatusSituationUnitConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.skillStatusSituationStatusCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSkillStatusSituationStatusCondition([NotNull] AttackSkillParser.SkillStatusSituationStatusConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.skillStatusSituationStatusCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSkillStatusSituationStatusCondition([NotNull] AttackSkillParser.SkillStatusSituationStatusConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.animSpeed"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnimSpeed([NotNull] AttackSkillParser.AnimSpeedContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.animSpeed"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnimSpeed([NotNull] AttackSkillParser.AnimSpeedContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.targetCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTargetCondition([NotNull] AttackSkillParser.TargetConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.targetCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTargetCondition([NotNull] AttackSkillParser.TargetConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.effectRange"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEffectRange([NotNull] AttackSkillParser.EffectRangeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.effectRange"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEffectRange([NotNull] AttackSkillParser.EffectRangeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.effectCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEffectCondition([NotNull] AttackSkillParser.EffectConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.effectCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEffectCondition([NotNull] AttackSkillParser.EffectConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.subSkill"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubSkill([NotNull] AttackSkillParser.SubSkillContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.subSkill"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubSkill([NotNull] AttackSkillParser.SubSkillContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.proxy"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProxy([NotNull] AttackSkillParser.ProxyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.proxy"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProxy([NotNull] AttackSkillParser.ProxyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.weaponReq"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWeaponReq([NotNull] AttackSkillParser.WeaponReqContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.weaponReq"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWeaponReq([NotNull] AttackSkillParser.WeaponReqContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.comboButton"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComboButton([NotNull] AttackSkillParser.ComboButtonContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.comboButton"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComboButton([NotNull] AttackSkillParser.ComboButtonContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.fxProjectileImpact"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFxProjectileImpact([NotNull] AttackSkillParser.FxProjectileImpactContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.fxProjectileImpact"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFxProjectileImpact([NotNull] AttackSkillParser.FxProjectileImpactContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.sound"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSound([NotNull] AttackSkillParser.SoundContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.sound"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSound([NotNull] AttackSkillParser.SoundContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.skillFree"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSkillFree([NotNull] AttackSkillParser.SkillFreeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.skillFree"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSkillFree([NotNull] AttackSkillParser.SkillFreeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.multiHitData"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiHitData([NotNull] AttackSkillParser.MultiHitDataContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.multiHitData"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiHitData([NotNull] AttackSkillParser.MultiHitDataContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.usabilityCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUsabilityCondition([NotNull] AttackSkillParser.UsabilityConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.usabilityCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUsabilityCondition([NotNull] AttackSkillParser.UsabilityConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.summonData"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSummonData([NotNull] AttackSkillParser.SummonDataContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.summonData"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSummonData([NotNull] AttackSkillParser.SummonDataContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.moveRange"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMoveRange([NotNull] AttackSkillParser.MoveRangeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.moveRange"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMoveRange([NotNull] AttackSkillParser.MoveRangeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.moveRangeCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMoveRangeCondition([NotNull] AttackSkillParser.MoveRangeConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.moveRangeCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMoveRangeCondition([NotNull] AttackSkillParser.MoveRangeConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.replaces"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReplaces([NotNull] AttackSkillParser.ReplacesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.replaces"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReplaces([NotNull] AttackSkillParser.ReplacesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.statusSituationSkillCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatusSituationSkillCondition([NotNull] AttackSkillParser.StatusSituationSkillConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.statusSituationSkillCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatusSituationSkillCondition([NotNull] AttackSkillParser.StatusSituationSkillConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.fxMove"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFxMove([NotNull] AttackSkillParser.FxMoveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.fxMove"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFxMove([NotNull] AttackSkillParser.FxMoveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.distanceDelay"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDistanceDelay([NotNull] AttackSkillParser.DistanceDelayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.distanceDelay"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDistanceDelay([NotNull] AttackSkillParser.DistanceDelayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AttackSkillParser.statusUseLimit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatusUseLimit([NotNull] AttackSkillParser.StatusUseLimitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AttackSkillParser.statusUseLimit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatusUseLimit([NotNull] AttackSkillParser.StatusUseLimitContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
