//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GladiusClassDef.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IGladiusClassDefListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class GladiusClassDefBaseListener : IGladiusClassDefListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.root"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRoot([NotNull] GladiusClassDefParser.RootContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.root"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRoot([NotNull] GladiusClassDefParser.RootContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.createClass"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCreateClass([NotNull] GladiusClassDefParser.CreateClassContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.createClass"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCreateClass([NotNull] GladiusClassDefParser.CreateClassContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.displayName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDisplayName([NotNull] GladiusClassDefParser.DisplayNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.displayName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDisplayName([NotNull] GladiusClassDefParser.DisplayNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.descriptionId"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDescriptionId([NotNull] GladiusClassDefParser.DescriptionIdContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.descriptionId"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDescriptionId([NotNull] GladiusClassDefParser.DescriptionIdContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.unitSet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnitSet([NotNull] GladiusClassDefParser.UnitSetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.unitSet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnitSet([NotNull] GladiusClassDefParser.UnitSetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.skillUse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSkillUse([NotNull] GladiusClassDefParser.SkillUseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.skillUse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSkillUse([NotNull] GladiusClassDefParser.SkillUseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.voiceLinePrefix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVoiceLinePrefix([NotNull] GladiusClassDefParser.VoiceLinePrefixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.voiceLinePrefix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVoiceLinePrefix([NotNull] GladiusClassDefParser.VoiceLinePrefixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.soundTable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSoundTable([NotNull] GladiusClassDefParser.SoundTableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.soundTable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSoundTable([NotNull] GladiusClassDefParser.SoundTableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.mesh"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMesh([NotNull] GladiusClassDefParser.MeshContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.mesh"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMesh([NotNull] GladiusClassDefParser.MeshContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.classIcon"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassIcon([NotNull] GladiusClassDefParser.ClassIconContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.classIcon"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassIcon([NotNull] GladiusClassDefParser.ClassIconContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.headIcon"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHeadIcon([NotNull] GladiusClassDefParser.HeadIconContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.headIcon"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHeadIcon([NotNull] GladiusClassDefParser.HeadIconContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.gridSize"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGridSize([NotNull] GladiusClassDefParser.GridSizeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.gridSize"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGridSize([NotNull] GladiusClassDefParser.GridSizeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.xpAward"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterXpAward([NotNull] GladiusClassDefParser.XpAwardContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.xpAward"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitXpAward([NotNull] GladiusClassDefParser.XpAwardContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.itemSizes"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterItemSizes([NotNull] GladiusClassDefParser.ItemSizesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.itemSizes"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitItemSizes([NotNull] GladiusClassDefParser.ItemSizesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.itemSubSize"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterItemSubSize([NotNull] GladiusClassDefParser.ItemSubSizeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.itemSubSize"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitItemSubSize([NotNull] GladiusClassDefParser.ItemSubSizeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttribute([NotNull] GladiusClassDefParser.AttributeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttribute([NotNull] GladiusClassDefParser.AttributeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.itemCat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterItemCat([NotNull] GladiusClassDefParser.ItemCatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.itemCat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitItemCat([NotNull] GladiusClassDefParser.ItemCatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.levelUpXpNeeded"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLevelUpXpNeeded([NotNull] GladiusClassDefParser.LevelUpXpNeededContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.levelUpXpNeeded"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLevelUpXpNeeded([NotNull] GladiusClassDefParser.LevelUpXpNeededContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.levelUpJPGiven"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLevelUpJPGiven([NotNull] GladiusClassDefParser.LevelUpJPGivenContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.levelUpJPGiven"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLevelUpJPGiven([NotNull] GladiusClassDefParser.LevelUpJPGivenContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.levelStatAwards"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLevelStatAwards([NotNull] GladiusClassDefParser.LevelStatAwardsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.levelStatAwards"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLevelStatAwards([NotNull] GladiusClassDefParser.LevelStatAwardsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.levelZeroStats"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLevelZeroStats([NotNull] GladiusClassDefParser.LevelZeroStatsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.levelZeroStats"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLevelZeroStats([NotNull] GladiusClassDefParser.LevelZeroStatsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.affinity"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAffinity([NotNull] GladiusClassDefParser.AffinityContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.affinity"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAffinity([NotNull] GladiusClassDefParser.AffinityContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.rockScissorsPaper"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRockScissorsPaper([NotNull] GladiusClassDefParser.RockScissorsPaperContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.rockScissorsPaper"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRockScissorsPaper([NotNull] GladiusClassDefParser.RockScissorsPaperContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.fx"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFx([NotNull] GladiusClassDefParser.FxContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.fx"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFx([NotNull] GladiusClassDefParser.FxContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.derivationClass"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDerivationClass([NotNull] GladiusClassDefParser.DerivationClassContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.derivationClass"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDerivationClass([NotNull] GladiusClassDefParser.DerivationClassContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.compileUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompileUnit([NotNull] GladiusClassDefParser.CompileUnitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.compileUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompileUnit([NotNull] GladiusClassDefParser.CompileUnitContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
