//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GladiusEncounter.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IGladiusEncounterListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class GladiusEncounterBaseListener : IGladiusEncounterListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusEncounterParser.root"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRoot([NotNull] GladiusEncounterParser.RootContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusEncounterParser.root"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRoot([NotNull] GladiusEncounterParser.RootContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusEncounterParser.encounterName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEncounterName([NotNull] GladiusEncounterParser.EncounterNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusEncounterParser.encounterName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEncounterName([NotNull] GladiusEncounterParser.EncounterNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusEncounterParser.ursulaEase"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUrsulaEase([NotNull] GladiusEncounterParser.UrsulaEaseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusEncounterParser.ursulaEase"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUrsulaEase([NotNull] GladiusEncounterParser.UrsulaEaseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusEncounterParser.valensEase"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValensEase([NotNull] GladiusEncounterParser.ValensEaseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusEncounterParser.valensEase"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValensEase([NotNull] GladiusEncounterParser.ValensEaseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusEncounterParser.prizeTier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrizeTier([NotNull] GladiusEncounterParser.PrizeTierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusEncounterParser.prizeTier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrizeTier([NotNull] GladiusEncounterParser.PrizeTierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusEncounterParser.scene"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScene([NotNull] GladiusEncounterParser.SceneContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusEncounterParser.scene"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScene([NotNull] GladiusEncounterParser.SceneContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusEncounterParser.gridFile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGridFile([NotNull] GladiusEncounterParser.GridFileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusEncounterParser.gridFile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGridFile([NotNull] GladiusEncounterParser.GridFileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusEncounterParser.propsFile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropsFile([NotNull] GladiusEncounterParser.PropsFileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusEncounterParser.propsFile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropsFile([NotNull] GladiusEncounterParser.PropsFileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusEncounterParser.music"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMusic([NotNull] GladiusEncounterParser.MusicContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusEncounterParser.music"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMusic([NotNull] GladiusEncounterParser.MusicContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusEncounterParser.battleScript"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBattleScript([NotNull] GladiusEncounterParser.BattleScriptContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusEncounterParser.battleScript"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBattleScript([NotNull] GladiusEncounterParser.BattleScriptContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusEncounterParser.cameraTrack"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCameraTrack([NotNull] GladiusEncounterParser.CameraTrackContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusEncounterParser.cameraTrack"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCameraTrack([NotNull] GladiusEncounterParser.CameraTrackContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusEncounterParser.totalPop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTotalPop([NotNull] GladiusEncounterParser.TotalPopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusEncounterParser.totalPop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTotalPop([NotNull] GladiusEncounterParser.TotalPopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusEncounterParser.crowdLevel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCrowdLevel([NotNull] GladiusEncounterParser.CrowdLevelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusEncounterParser.crowdLevel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCrowdLevel([NotNull] GladiusEncounterParser.CrowdLevelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusEncounterParser.candie"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCandie([NotNull] GladiusEncounterParser.CandieContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusEncounterParser.candie"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCandie([NotNull] GladiusEncounterParser.CandieContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusEncounterParser.cutscene"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCutscene([NotNull] GladiusEncounterParser.CutsceneContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusEncounterParser.cutscene"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCutscene([NotNull] GladiusEncounterParser.CutsceneContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusEncounterParser.team"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTeam([NotNull] GladiusEncounterParser.TeamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusEncounterParser.team"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTeam([NotNull] GladiusEncounterParser.TeamContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusEncounterParser.school"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSchool([NotNull] GladiusEncounterParser.SchoolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusEncounterParser.school"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSchool([NotNull] GladiusEncounterParser.SchoolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusEncounterParser.unitDB"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnitDB([NotNull] GladiusEncounterParser.UnitDBContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusEncounterParser.unitDB"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnitDB([NotNull] GladiusEncounterParser.UnitDBContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
