//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GladiusItem.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="GladiusItemParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IGladiusItemVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusItemParser.root"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRoot([NotNull] GladiusItemParser.RootContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusItemParser.numEntries"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumEntries([NotNull] GladiusItemParser.NumEntriesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusItemParser.item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitItem([NotNull] GladiusItemParser.ItemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusItemParser.itemCreate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitItemCreate([NotNull] GladiusItemParser.ItemCreateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusItemParser.itemDescriptionId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitItemDescriptionId([NotNull] GladiusItemParser.ItemDescriptionIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusItemParser.itemDisplayNameId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitItemDisplayNameId([NotNull] GladiusItemParser.ItemDisplayNameIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusItemParser.itemCost"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitItemCost([NotNull] GladiusItemParser.ItemCostContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusItemParser.itemMinLevel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitItemMinLevel([NotNull] GladiusItemParser.ItemMinLevelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusItemParser.itemRarity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitItemRarity([NotNull] GladiusItemParser.ItemRarityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusItemParser.itemRegion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitItemRegion([NotNull] GladiusItemParser.ItemRegionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusItemParser.itemHideSet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitItemHideSet([NotNull] GladiusItemParser.ItemHideSetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusItemParser.itemShowSet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitItemShowSet([NotNull] GladiusItemParser.ItemShowSetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusItemParser.itemMesh"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitItemMesh([NotNull] GladiusItemParser.ItemMeshContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusItemParser.itemMaterial"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitItemMaterial([NotNull] GladiusItemParser.ItemMaterialContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusItemParser.itemSkill"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitItemSkill([NotNull] GladiusItemParser.ItemSkillContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusItemParser.itemAffinity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitItemAffinity([NotNull] GladiusItemParser.ItemAffinityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusItemParser.itemStatMod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitItemStatMod([NotNull] GladiusItemParser.ItemStatModContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusItemParser.itemAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitItemAttribute([NotNull] GladiusItemParser.ItemAttributeContext context);
}
