//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GladiusItemSet.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class GladiusItemSetLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, WS=5, INT=6, FLOAT=7, COMMA=8, UNDERSCORE=9, 
		DASH=10, ITEMNAME=11, STRING=12, SINGLELINE_COMMENT=13;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "WS", "INT", "FLOAT", "COMMA", "UNDERSCORE", 
		"DASH", "ITEMNAME", "STRING", "ESC", "UNICODE", "HEX", "SINGLELINE_COMMENT"
	};


	public GladiusItemSetLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public GladiusItemSetLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'ITEMSET export Class:'", "'Region:'", "'Affinity:'", "'MODITEMSCOMP:'", 
		null, null, null, "','", "'_'", "'-'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, "WS", "INT", "FLOAT", "COMMA", "UNDERSCORE", 
		"DASH", "ITEMNAME", "STRING", "SINGLELINE_COMMENT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "GladiusItemSet.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static GladiusItemSetLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\xF', '\xAB', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x6', '\x6', '\x6', '[', '\n', '\x6', '\r', '\x6', '\xE', 
		'\x6', '\\', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x5', '\a', '\x62', 
		'\n', '\a', '\x3', '\a', '\x6', '\a', '\x65', '\n', '\a', '\r', '\a', 
		'\xE', '\a', '\x66', '\x3', '\b', '\x5', '\b', 'j', '\n', '\b', '\x3', 
		'\b', '\x6', '\b', 'm', '\n', '\b', '\r', '\b', '\xE', '\b', 'n', '\x3', 
		'\b', '\x3', '\b', '\x6', '\b', 's', '\n', '\b', '\r', '\b', '\xE', '\b', 
		't', '\x5', '\b', 'w', '\n', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\n', 
		'\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\a', '\f', '\x82', '\n', '\f', '\f', '\f', '\xE', '\f', '\x85', 
		'\v', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x5', '\r', '\x8A', 
		'\n', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\a', '\r', '\x8F', 
		'\n', '\r', '\f', '\r', '\xE', '\r', '\x92', '\v', '\r', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x5', '\xE', '\x97', '\n', '\xE', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x11', '\x3', '\x11', '\a', '\x11', '\xA5', '\n', '\x11', '\f', '\x11', 
		'\xE', '\x11', '\xA8', '\v', '\x11', '\x3', '\x11', '\x3', '\x11', '\x2', 
		'\x2', '\x12', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', 
		'\a', '\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', 
		'\x17', '\r', '\x19', '\xE', '\x1B', '\x2', '\x1D', '\x2', '\x1F', '\x2', 
		'!', '\xF', '\x3', '\x2', '\n', '\x5', '\x2', '\v', '\f', '\xF', '\xF', 
		'\"', '\"', '\x3', '\x2', '\x32', ';', '\x3', '\x2', '$', '$', '\x4', 
		'\x2', '\x43', '\\', '\x63', '|', '\a', '\x2', ')', ')', '\x32', ';', 
		'\x43', '\\', '^', '^', '\x63', '|', '\n', '\x2', '$', '$', '\x31', '\x31', 
		'^', '^', '\x64', '\x64', 'h', 'h', 'p', 'p', 't', 't', 'v', 'v', '\x5', 
		'\x2', '\x32', ';', '\x43', 'H', '\x63', 'h', '\x4', '\x2', '\f', '\f', 
		'\xF', '\xF', '\x2', '\xB5', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x13', '\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x3', '#', 
		'\x3', '\x2', '\x2', '\x2', '\x5', '\x39', '\x3', '\x2', '\x2', '\x2', 
		'\a', '\x41', '\x3', '\x2', '\x2', '\x2', '\t', 'K', '\x3', '\x2', '\x2', 
		'\x2', '\v', 'Z', '\x3', '\x2', '\x2', '\x2', '\r', '\x61', '\x3', '\x2', 
		'\x2', '\x2', '\xF', 'i', '\x3', '\x2', '\x2', '\x2', '\x11', 'x', '\x3', 
		'\x2', '\x2', '\x2', '\x13', 'z', '\x3', '\x2', '\x2', '\x2', '\x15', 
		'|', '\x3', '\x2', '\x2', '\x2', '\x17', '~', '\x3', '\x2', '\x2', '\x2', 
		'\x19', '\x89', '\x3', '\x2', '\x2', '\x2', '\x1B', '\x93', '\x3', '\x2', 
		'\x2', '\x2', '\x1D', '\x98', '\x3', '\x2', '\x2', '\x2', '\x1F', '\x9E', 
		'\x3', '\x2', '\x2', '\x2', '!', '\xA0', '\x3', '\x2', '\x2', '\x2', '#', 
		'$', '\a', 'K', '\x2', '\x2', '$', '%', '\a', 'V', '\x2', '\x2', '%', 
		'&', '\a', 'G', '\x2', '\x2', '&', '\'', '\a', 'O', '\x2', '\x2', '\'', 
		'(', '\a', 'U', '\x2', '\x2', '(', ')', '\a', 'G', '\x2', '\x2', ')', 
		'*', '\a', 'V', '\x2', '\x2', '*', '+', '\a', '\"', '\x2', '\x2', '+', 
		',', '\a', 'g', '\x2', '\x2', ',', '-', '\a', 'z', '\x2', '\x2', '-', 
		'.', '\a', 'r', '\x2', '\x2', '.', '/', '\a', 'q', '\x2', '\x2', '/', 
		'\x30', '\a', 't', '\x2', '\x2', '\x30', '\x31', '\a', 'v', '\x2', '\x2', 
		'\x31', '\x32', '\a', '\"', '\x2', '\x2', '\x32', '\x33', '\a', '\x45', 
		'\x2', '\x2', '\x33', '\x34', '\a', 'n', '\x2', '\x2', '\x34', '\x35', 
		'\a', '\x63', '\x2', '\x2', '\x35', '\x36', '\a', 'u', '\x2', '\x2', '\x36', 
		'\x37', '\a', 'u', '\x2', '\x2', '\x37', '\x38', '\a', '<', '\x2', '\x2', 
		'\x38', '\x4', '\x3', '\x2', '\x2', '\x2', '\x39', ':', '\a', 'T', '\x2', 
		'\x2', ':', ';', '\a', 'g', '\x2', '\x2', ';', '<', '\a', 'i', '\x2', 
		'\x2', '<', '=', '\a', 'k', '\x2', '\x2', '=', '>', '\a', 'q', '\x2', 
		'\x2', '>', '?', '\a', 'p', '\x2', '\x2', '?', '@', '\a', '<', '\x2', 
		'\x2', '@', '\x6', '\x3', '\x2', '\x2', '\x2', '\x41', '\x42', '\a', '\x43', 
		'\x2', '\x2', '\x42', '\x43', '\a', 'h', '\x2', '\x2', '\x43', '\x44', 
		'\a', 'h', '\x2', '\x2', '\x44', '\x45', '\a', 'k', '\x2', '\x2', '\x45', 
		'\x46', '\a', 'p', '\x2', '\x2', '\x46', 'G', '\a', 'k', '\x2', '\x2', 
		'G', 'H', '\a', 'v', '\x2', '\x2', 'H', 'I', '\a', '{', '\x2', '\x2', 
		'I', 'J', '\a', '<', '\x2', '\x2', 'J', '\b', '\x3', '\x2', '\x2', '\x2', 
		'K', 'L', '\a', 'O', '\x2', '\x2', 'L', 'M', '\a', 'Q', '\x2', '\x2', 
		'M', 'N', '\a', '\x46', '\x2', '\x2', 'N', 'O', '\a', 'K', '\x2', '\x2', 
		'O', 'P', '\a', 'V', '\x2', '\x2', 'P', 'Q', '\a', 'G', '\x2', '\x2', 
		'Q', 'R', '\a', 'O', '\x2', '\x2', 'R', 'S', '\a', 'U', '\x2', '\x2', 
		'S', 'T', '\a', '\x45', '\x2', '\x2', 'T', 'U', '\a', 'Q', '\x2', '\x2', 
		'U', 'V', '\a', 'O', '\x2', '\x2', 'V', 'W', '\a', 'R', '\x2', '\x2', 
		'W', 'X', '\a', '<', '\x2', '\x2', 'X', '\n', '\x3', '\x2', '\x2', '\x2', 
		'Y', '[', '\t', '\x2', '\x2', '\x2', 'Z', 'Y', '\x3', '\x2', '\x2', '\x2', 
		'[', '\\', '\x3', '\x2', '\x2', '\x2', '\\', 'Z', '\x3', '\x2', '\x2', 
		'\x2', '\\', ']', '\x3', '\x2', '\x2', '\x2', ']', '^', '\x3', '\x2', 
		'\x2', '\x2', '^', '_', '\b', '\x6', '\x2', '\x2', '_', '\f', '\x3', '\x2', 
		'\x2', '\x2', '`', '\x62', '\a', '/', '\x2', '\x2', '\x61', '`', '\x3', 
		'\x2', '\x2', '\x2', '\x61', '\x62', '\x3', '\x2', '\x2', '\x2', '\x62', 
		'\x64', '\x3', '\x2', '\x2', '\x2', '\x63', '\x65', '\t', '\x3', '\x2', 
		'\x2', '\x64', '\x63', '\x3', '\x2', '\x2', '\x2', '\x65', '\x66', '\x3', 
		'\x2', '\x2', '\x2', '\x66', '\x64', '\x3', '\x2', '\x2', '\x2', '\x66', 
		'g', '\x3', '\x2', '\x2', '\x2', 'g', '\xE', '\x3', '\x2', '\x2', '\x2', 
		'h', 'j', '\a', '/', '\x2', '\x2', 'i', 'h', '\x3', '\x2', '\x2', '\x2', 
		'i', 'j', '\x3', '\x2', '\x2', '\x2', 'j', 'l', '\x3', '\x2', '\x2', '\x2', 
		'k', 'm', '\t', '\x3', '\x2', '\x2', 'l', 'k', '\x3', '\x2', '\x2', '\x2', 
		'm', 'n', '\x3', '\x2', '\x2', '\x2', 'n', 'l', '\x3', '\x2', '\x2', '\x2', 
		'n', 'o', '\x3', '\x2', '\x2', '\x2', 'o', 'v', '\x3', '\x2', '\x2', '\x2', 
		'p', 'r', '\a', '\x30', '\x2', '\x2', 'q', 's', '\t', '\x3', '\x2', '\x2', 
		'r', 'q', '\x3', '\x2', '\x2', '\x2', 's', 't', '\x3', '\x2', '\x2', '\x2', 
		't', 'r', '\x3', '\x2', '\x2', '\x2', 't', 'u', '\x3', '\x2', '\x2', '\x2', 
		'u', 'w', '\x3', '\x2', '\x2', '\x2', 'v', 'p', '\x3', '\x2', '\x2', '\x2', 
		'v', 'w', '\x3', '\x2', '\x2', '\x2', 'w', '\x10', '\x3', '\x2', '\x2', 
		'\x2', 'x', 'y', '\a', '.', '\x2', '\x2', 'y', '\x12', '\x3', '\x2', '\x2', 
		'\x2', 'z', '{', '\a', '\x61', '\x2', '\x2', '{', '\x14', '\x3', '\x2', 
		'\x2', '\x2', '|', '}', '\a', '/', '\x2', '\x2', '}', '\x16', '\x3', '\x2', 
		'\x2', '\x2', '~', '\x83', '\a', '$', '\x2', '\x2', '\x7F', '\x82', '\x5', 
		'\x1B', '\xE', '\x2', '\x80', '\x82', '\n', '\x4', '\x2', '\x2', '\x81', 
		'\x7F', '\x3', '\x2', '\x2', '\x2', '\x81', '\x80', '\x3', '\x2', '\x2', 
		'\x2', '\x82', '\x85', '\x3', '\x2', '\x2', '\x2', '\x83', '\x81', '\x3', 
		'\x2', '\x2', '\x2', '\x83', '\x84', '\x3', '\x2', '\x2', '\x2', '\x84', 
		'\x86', '\x3', '\x2', '\x2', '\x2', '\x85', '\x83', '\x3', '\x2', '\x2', 
		'\x2', '\x86', '\x87', '\a', '$', '\x2', '\x2', '\x87', '\x18', '\x3', 
		'\x2', '\x2', '\x2', '\x88', '\x8A', '\t', '\x5', '\x2', '\x2', '\x89', 
		'\x88', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x90', '\x3', '\x2', '\x2', 
		'\x2', '\x8B', '\x8F', '\t', '\x6', '\x2', '\x2', '\x8C', '\x8F', '\x5', 
		'\x13', '\n', '\x2', '\x8D', '\x8F', '\x5', '\x15', '\v', '\x2', '\x8E', 
		'\x8B', '\x3', '\x2', '\x2', '\x2', '\x8E', '\x8C', '\x3', '\x2', '\x2', 
		'\x2', '\x8E', '\x8D', '\x3', '\x2', '\x2', '\x2', '\x8F', '\x92', '\x3', 
		'\x2', '\x2', '\x2', '\x90', '\x8E', '\x3', '\x2', '\x2', '\x2', '\x90', 
		'\x91', '\x3', '\x2', '\x2', '\x2', '\x91', '\x1A', '\x3', '\x2', '\x2', 
		'\x2', '\x92', '\x90', '\x3', '\x2', '\x2', '\x2', '\x93', '\x96', '\a', 
		'^', '\x2', '\x2', '\x94', '\x97', '\t', '\a', '\x2', '\x2', '\x95', '\x97', 
		'\x5', '\x1D', '\xF', '\x2', '\x96', '\x94', '\x3', '\x2', '\x2', '\x2', 
		'\x96', '\x95', '\x3', '\x2', '\x2', '\x2', '\x97', '\x1C', '\x3', '\x2', 
		'\x2', '\x2', '\x98', '\x99', '\a', 'w', '\x2', '\x2', '\x99', '\x9A', 
		'\x5', '\x1F', '\x10', '\x2', '\x9A', '\x9B', '\x5', '\x1F', '\x10', '\x2', 
		'\x9B', '\x9C', '\x5', '\x1F', '\x10', '\x2', '\x9C', '\x9D', '\x5', '\x1F', 
		'\x10', '\x2', '\x9D', '\x1E', '\x3', '\x2', '\x2', '\x2', '\x9E', '\x9F', 
		'\t', '\b', '\x2', '\x2', '\x9F', ' ', '\x3', '\x2', '\x2', '\x2', '\xA0', 
		'\xA1', '\a', '\x31', '\x2', '\x2', '\xA1', '\xA2', '\a', '\x31', '\x2', 
		'\x2', '\xA2', '\xA6', '\x3', '\x2', '\x2', '\x2', '\xA3', '\xA5', '\n', 
		'\t', '\x2', '\x2', '\xA4', '\xA3', '\x3', '\x2', '\x2', '\x2', '\xA5', 
		'\xA8', '\x3', '\x2', '\x2', '\x2', '\xA6', '\xA4', '\x3', '\x2', '\x2', 
		'\x2', '\xA6', '\xA7', '\x3', '\x2', '\x2', '\x2', '\xA7', '\xA9', '\x3', 
		'\x2', '\x2', '\x2', '\xA8', '\xA6', '\x3', '\x2', '\x2', '\x2', '\xA9', 
		'\xAA', '\b', '\x11', '\x2', '\x2', '\xAA', '\"', '\x3', '\x2', '\x2', 
		'\x2', '\x11', '\x2', '\\', '\x61', '\x66', 'i', 'n', 't', 'v', '\x81', 
		'\x83', '\x89', '\x8E', '\x90', '\x96', '\xA6', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
