//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GladiusLeague.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="GladiusLeagueParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IGladiusLeagueVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusLeagueParser.root"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRoot([NotNull] GladiusLeagueParser.RootContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusLeagueParser.officeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOfficeName([NotNull] GladiusLeagueParser.OfficeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusLeagueParser.officeDesc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOfficeDesc([NotNull] GladiusLeagueParser.OfficeDescContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusLeagueParser.tagLine1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTagLine1([NotNull] GladiusLeagueParser.TagLine1Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusLeagueParser.tagLine2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTagLine2([NotNull] GladiusLeagueParser.TagLine2Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusLeagueParser.leaguePtsNeeded"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLeaguePtsNeeded([NotNull] GladiusLeagueParser.LeaguePtsNeededContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusLeagueParser.officer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOfficer([NotNull] GladiusLeagueParser.OfficerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusLeagueParser.recruit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRecruit([NotNull] GladiusLeagueParser.RecruitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusLeagueParser.school"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSchool([NotNull] GladiusLeagueParser.SchoolContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusLeagueParser.league"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLeague([NotNull] GladiusLeagueParser.LeagueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusLeagueParser.leagueDesc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLeagueDesc([NotNull] GladiusLeagueParser.LeagueDescContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusLeagueParser.leaguePts"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLeaguePts([NotNull] GladiusLeagueParser.LeaguePtsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusLeagueParser.encptsNeeded"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEncptsNeeded([NotNull] GladiusLeagueParser.EncptsNeededContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusLeagueParser.onHover"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOnHover([NotNull] GladiusLeagueParser.OnHoverContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusLeagueParser.onSelect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOnSelect([NotNull] GladiusLeagueParser.OnSelectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusLeagueParser.onWin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOnWin([NotNull] GladiusLeagueParser.OnWinContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusLeagueParser.designNotes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDesignNotes([NotNull] GladiusLeagueParser.DesignNotesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusLeagueParser.minPop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMinPop([NotNull] GladiusLeagueParser.MinPopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusLeagueParser.tier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTier([NotNull] GladiusLeagueParser.TierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusLeagueParser.badge"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBadge([NotNull] GladiusLeagueParser.BadgeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusLeagueParser.prizeCompletion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrizeCompletion([NotNull] GladiusLeagueParser.PrizeCompletionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusLeagueParser.prizeMastery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrizeMastery([NotNull] GladiusLeagueParser.PrizeMasteryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusLeagueParser.encounter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEncounter([NotNull] GladiusLeagueParser.EncounterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusLeagueParser.encDesc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEncDesc([NotNull] GladiusLeagueParser.EncDescContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusLeagueParser.encFile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEncFile([NotNull] GladiusLeagueParser.EncFileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusLeagueParser.encpts"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEncpts([NotNull] GladiusLeagueParser.EncptsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusLeagueParser.teams"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTeams([NotNull] GladiusLeagueParser.TeamsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusLeagueParser.frequency"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFrequency([NotNull] GladiusLeagueParser.FrequencyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusLeagueParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] GladiusLeagueParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusLeagueParser.entryFee"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntryFee([NotNull] GladiusLeagueParser.EntryFeeContext context);
}
