//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GladiusClassDef.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="GladiusClassDefParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IGladiusClassDefVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusClassDefParser.root"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRoot([NotNull] GladiusClassDefParser.RootContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusClassDefParser.createClass"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreateClass([NotNull] GladiusClassDefParser.CreateClassContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusClassDefParser.displayName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDisplayName([NotNull] GladiusClassDefParser.DisplayNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusClassDefParser.descriptionId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDescriptionId([NotNull] GladiusClassDefParser.DescriptionIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusClassDefParser.unitSet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnitSet([NotNull] GladiusClassDefParser.UnitSetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusClassDefParser.skillUse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSkillUse([NotNull] GladiusClassDefParser.SkillUseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusClassDefParser.voiceLinePrefix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVoiceLinePrefix([NotNull] GladiusClassDefParser.VoiceLinePrefixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusClassDefParser.soundTable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSoundTable([NotNull] GladiusClassDefParser.SoundTableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusClassDefParser.mesh"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMesh([NotNull] GladiusClassDefParser.MeshContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusClassDefParser.classIcon"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassIcon([NotNull] GladiusClassDefParser.ClassIconContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusClassDefParser.headIcon"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHeadIcon([NotNull] GladiusClassDefParser.HeadIconContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusClassDefParser.gridSize"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGridSize([NotNull] GladiusClassDefParser.GridSizeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusClassDefParser.xpAward"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitXpAward([NotNull] GladiusClassDefParser.XpAwardContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusClassDefParser.itemSizes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitItemSizes([NotNull] GladiusClassDefParser.ItemSizesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusClassDefParser.itemSubSize"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitItemSubSize([NotNull] GladiusClassDefParser.ItemSubSizeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusClassDefParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute([NotNull] GladiusClassDefParser.AttributeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusClassDefParser.itemCat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitItemCat([NotNull] GladiusClassDefParser.ItemCatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusClassDefParser.levelUpXpNeeded"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLevelUpXpNeeded([NotNull] GladiusClassDefParser.LevelUpXpNeededContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusClassDefParser.levelUpJPGiven"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLevelUpJPGiven([NotNull] GladiusClassDefParser.LevelUpJPGivenContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusClassDefParser.levelStatAwards"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLevelStatAwards([NotNull] GladiusClassDefParser.LevelStatAwardsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusClassDefParser.levelZeroStats"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLevelZeroStats([NotNull] GladiusClassDefParser.LevelZeroStatsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusClassDefParser.affinity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAffinity([NotNull] GladiusClassDefParser.AffinityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusClassDefParser.rockScissorsPaper"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRockScissorsPaper([NotNull] GladiusClassDefParser.RockScissorsPaperContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusClassDefParser.fx"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFx([NotNull] GladiusClassDefParser.FxContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusClassDefParser.derivationClass"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDerivationClass([NotNull] GladiusClassDefParser.DerivationClassContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GladiusClassDefParser.compileUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompileUnit([NotNull] GladiusClassDefParser.CompileUnitContext context);
}
