//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GladiusEncounter.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="GladiusEncounterParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IGladiusEncounterListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusEncounterParser.root"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRoot([NotNull] GladiusEncounterParser.RootContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusEncounterParser.root"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRoot([NotNull] GladiusEncounterParser.RootContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusEncounterParser.encounterName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEncounterName([NotNull] GladiusEncounterParser.EncounterNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusEncounterParser.encounterName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEncounterName([NotNull] GladiusEncounterParser.EncounterNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusEncounterParser.ursulaEase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUrsulaEase([NotNull] GladiusEncounterParser.UrsulaEaseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusEncounterParser.ursulaEase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUrsulaEase([NotNull] GladiusEncounterParser.UrsulaEaseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusEncounterParser.valensEase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValensEase([NotNull] GladiusEncounterParser.ValensEaseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusEncounterParser.valensEase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValensEase([NotNull] GladiusEncounterParser.ValensEaseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusEncounterParser.prizeTier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrizeTier([NotNull] GladiusEncounterParser.PrizeTierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusEncounterParser.prizeTier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrizeTier([NotNull] GladiusEncounterParser.PrizeTierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusEncounterParser.scene"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScene([NotNull] GladiusEncounterParser.SceneContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusEncounterParser.scene"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScene([NotNull] GladiusEncounterParser.SceneContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusEncounterParser.gridFile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGridFile([NotNull] GladiusEncounterParser.GridFileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusEncounterParser.gridFile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGridFile([NotNull] GladiusEncounterParser.GridFileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusEncounterParser.propsFile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropsFile([NotNull] GladiusEncounterParser.PropsFileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusEncounterParser.propsFile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropsFile([NotNull] GladiusEncounterParser.PropsFileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusEncounterParser.music"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMusic([NotNull] GladiusEncounterParser.MusicContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusEncounterParser.music"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMusic([NotNull] GladiusEncounterParser.MusicContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusEncounterParser.battleScript"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBattleScript([NotNull] GladiusEncounterParser.BattleScriptContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusEncounterParser.battleScript"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBattleScript([NotNull] GladiusEncounterParser.BattleScriptContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusEncounterParser.cameraTrack"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCameraTrack([NotNull] GladiusEncounterParser.CameraTrackContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusEncounterParser.cameraTrack"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCameraTrack([NotNull] GladiusEncounterParser.CameraTrackContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusEncounterParser.totalPop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTotalPop([NotNull] GladiusEncounterParser.TotalPopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusEncounterParser.totalPop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTotalPop([NotNull] GladiusEncounterParser.TotalPopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusEncounterParser.crowdLevel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCrowdLevel([NotNull] GladiusEncounterParser.CrowdLevelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusEncounterParser.crowdLevel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCrowdLevel([NotNull] GladiusEncounterParser.CrowdLevelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusEncounterParser.candie"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCandie([NotNull] GladiusEncounterParser.CandieContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusEncounterParser.candie"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCandie([NotNull] GladiusEncounterParser.CandieContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusEncounterParser.cutscene"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCutscene([NotNull] GladiusEncounterParser.CutsceneContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusEncounterParser.cutscene"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCutscene([NotNull] GladiusEncounterParser.CutsceneContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusEncounterParser.team"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTeam([NotNull] GladiusEncounterParser.TeamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusEncounterParser.team"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTeam([NotNull] GladiusEncounterParser.TeamContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusEncounterParser.school"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSchool([NotNull] GladiusEncounterParser.SchoolContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusEncounterParser.school"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSchool([NotNull] GladiusEncounterParser.SchoolContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusEncounterParser.unitDB"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnitDB([NotNull] GladiusEncounterParser.UnitDBContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusEncounterParser.unitDB"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnitDB([NotNull] GladiusEncounterParser.UnitDBContext context);
}
