//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GladiusClassDef.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="GladiusClassDefParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IGladiusClassDefListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.root"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRoot([NotNull] GladiusClassDefParser.RootContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.root"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRoot([NotNull] GladiusClassDefParser.RootContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.createClass"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCreateClass([NotNull] GladiusClassDefParser.CreateClassContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.createClass"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCreateClass([NotNull] GladiusClassDefParser.CreateClassContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.displayName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDisplayName([NotNull] GladiusClassDefParser.DisplayNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.displayName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDisplayName([NotNull] GladiusClassDefParser.DisplayNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.descriptionId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDescriptionId([NotNull] GladiusClassDefParser.DescriptionIdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.descriptionId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDescriptionId([NotNull] GladiusClassDefParser.DescriptionIdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.unitSet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnitSet([NotNull] GladiusClassDefParser.UnitSetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.unitSet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnitSet([NotNull] GladiusClassDefParser.UnitSetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.skillUse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSkillUse([NotNull] GladiusClassDefParser.SkillUseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.skillUse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSkillUse([NotNull] GladiusClassDefParser.SkillUseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.voiceLinePrefix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVoiceLinePrefix([NotNull] GladiusClassDefParser.VoiceLinePrefixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.voiceLinePrefix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVoiceLinePrefix([NotNull] GladiusClassDefParser.VoiceLinePrefixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.soundTable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSoundTable([NotNull] GladiusClassDefParser.SoundTableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.soundTable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSoundTable([NotNull] GladiusClassDefParser.SoundTableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.mesh"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMesh([NotNull] GladiusClassDefParser.MeshContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.mesh"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMesh([NotNull] GladiusClassDefParser.MeshContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.classIcon"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassIcon([NotNull] GladiusClassDefParser.ClassIconContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.classIcon"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassIcon([NotNull] GladiusClassDefParser.ClassIconContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.headIcon"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHeadIcon([NotNull] GladiusClassDefParser.HeadIconContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.headIcon"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHeadIcon([NotNull] GladiusClassDefParser.HeadIconContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.gridSize"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGridSize([NotNull] GladiusClassDefParser.GridSizeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.gridSize"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGridSize([NotNull] GladiusClassDefParser.GridSizeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.xpAward"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterXpAward([NotNull] GladiusClassDefParser.XpAwardContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.xpAward"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitXpAward([NotNull] GladiusClassDefParser.XpAwardContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.itemSizes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterItemSizes([NotNull] GladiusClassDefParser.ItemSizesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.itemSizes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitItemSizes([NotNull] GladiusClassDefParser.ItemSizesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.itemSubSize"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterItemSubSize([NotNull] GladiusClassDefParser.ItemSubSizeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.itemSubSize"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitItemSubSize([NotNull] GladiusClassDefParser.ItemSubSizeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttribute([NotNull] GladiusClassDefParser.AttributeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttribute([NotNull] GladiusClassDefParser.AttributeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.itemCat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterItemCat([NotNull] GladiusClassDefParser.ItemCatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.itemCat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitItemCat([NotNull] GladiusClassDefParser.ItemCatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.levelUpXpNeeded"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLevelUpXpNeeded([NotNull] GladiusClassDefParser.LevelUpXpNeededContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.levelUpXpNeeded"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLevelUpXpNeeded([NotNull] GladiusClassDefParser.LevelUpXpNeededContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.levelUpJPGiven"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLevelUpJPGiven([NotNull] GladiusClassDefParser.LevelUpJPGivenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.levelUpJPGiven"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLevelUpJPGiven([NotNull] GladiusClassDefParser.LevelUpJPGivenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.levelStatAwards"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLevelStatAwards([NotNull] GladiusClassDefParser.LevelStatAwardsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.levelStatAwards"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLevelStatAwards([NotNull] GladiusClassDefParser.LevelStatAwardsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.levelZeroStats"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLevelZeroStats([NotNull] GladiusClassDefParser.LevelZeroStatsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.levelZeroStats"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLevelZeroStats([NotNull] GladiusClassDefParser.LevelZeroStatsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.affinity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAffinity([NotNull] GladiusClassDefParser.AffinityContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.affinity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAffinity([NotNull] GladiusClassDefParser.AffinityContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.rockScissorsPaper"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRockScissorsPaper([NotNull] GladiusClassDefParser.RockScissorsPaperContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.rockScissorsPaper"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRockScissorsPaper([NotNull] GladiusClassDefParser.RockScissorsPaperContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.fx"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFx([NotNull] GladiusClassDefParser.FxContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.fx"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFx([NotNull] GladiusClassDefParser.FxContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.derivationClass"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDerivationClass([NotNull] GladiusClassDefParser.DerivationClassContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.derivationClass"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDerivationClass([NotNull] GladiusClassDefParser.DerivationClassContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusClassDefParser.compileUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompileUnit([NotNull] GladiusClassDefParser.CompileUnitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusClassDefParser.compileUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompileUnit([NotNull] GladiusClassDefParser.CompileUnitContext context);
}
