//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GladiusProps.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="GladiusPropsParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IGladiusPropsListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusPropsParser.root"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRoot([NotNull] GladiusPropsParser.RootContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusPropsParser.root"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRoot([NotNull] GladiusPropsParser.RootContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusPropsParser.version"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVersion([NotNull] GladiusPropsParser.VersionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusPropsParser.version"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVersion([NotNull] GladiusPropsParser.VersionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusPropsParser.prop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProp([NotNull] GladiusPropsParser.PropContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusPropsParser.prop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProp([NotNull] GladiusPropsParser.PropContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusPropsParser.propname"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropname([NotNull] GladiusPropsParser.PropnameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusPropsParser.propname"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropname([NotNull] GladiusPropsParser.PropnameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusPropsParser.models"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModels([NotNull] GladiusPropsParser.ModelsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusPropsParser.models"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModels([NotNull] GladiusPropsParser.ModelsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusPropsParser.lighting"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLighting([NotNull] GladiusPropsParser.LightingContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusPropsParser.lighting"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLighting([NotNull] GladiusPropsParser.LightingContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusPropsParser.shadow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShadow([NotNull] GladiusPropsParser.ShadowContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusPropsParser.shadow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShadow([NotNull] GladiusPropsParser.ShadowContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusPropsParser.scriptname"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScriptname([NotNull] GladiusPropsParser.ScriptnameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusPropsParser.scriptname"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScriptname([NotNull] GladiusPropsParser.ScriptnameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusPropsParser.heights"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHeights([NotNull] GladiusPropsParser.HeightsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusPropsParser.heights"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHeights([NotNull] GladiusPropsParser.HeightsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusPropsParser.heightsoffset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHeightsoffset([NotNull] GladiusPropsParser.HeightsoffsetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusPropsParser.heightsoffset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHeightsoffset([NotNull] GladiusPropsParser.HeightsoffsetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusPropsParser.pos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPos([NotNull] GladiusPropsParser.PosContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusPropsParser.pos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPos([NotNull] GladiusPropsParser.PosContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusPropsParser.rot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRot([NotNull] GladiusPropsParser.RotContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusPropsParser.rot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRot([NotNull] GladiusPropsParser.RotContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusPropsParser.attributescount"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttributescount([NotNull] GladiusPropsParser.AttributescountContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusPropsParser.attributescount"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttributescount([NotNull] GladiusPropsParser.AttributescountContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusPropsParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttribute([NotNull] GladiusPropsParser.AttributeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusPropsParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttribute([NotNull] GladiusPropsParser.AttributeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusPropsParser.propend"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropend([NotNull] GladiusPropsParser.PropendContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusPropsParser.propend"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropend([NotNull] GladiusPropsParser.PropendContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusPropsParser.onoff"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOnoff([NotNull] GladiusPropsParser.OnoffContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusPropsParser.onoff"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOnoff([NotNull] GladiusPropsParser.OnoffContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusPropsParser.endfile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEndfile([NotNull] GladiusPropsParser.EndfileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusPropsParser.endfile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEndfile([NotNull] GladiusPropsParser.EndfileContext context);
}
