//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GladiusJournal.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="GladiusJournalParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IGladiusJournalListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusJournalParser.root"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRoot([NotNull] GladiusJournalParser.RootContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusJournalParser.root"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRoot([NotNull] GladiusJournalParser.RootContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusJournalParser.rumour"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRumour([NotNull] GladiusJournalParser.RumourContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusJournalParser.rumour"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRumour([NotNull] GladiusJournalParser.RumourContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusJournalParser.conversation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConversation([NotNull] GladiusJournalParser.ConversationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusJournalParser.conversation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConversation([NotNull] GladiusJournalParser.ConversationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusJournalParser.minDays"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMinDays([NotNull] GladiusJournalParser.MinDaysContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusJournalParser.minDays"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMinDays([NotNull] GladiusJournalParser.MinDaysContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusJournalParser.ursulaChoice"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUrsulaChoice([NotNull] GladiusJournalParser.UrsulaChoiceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusJournalParser.ursulaChoice"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUrsulaChoice([NotNull] GladiusJournalParser.UrsulaChoiceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusJournalParser.valensChoice"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValensChoice([NotNull] GladiusJournalParser.ValensChoiceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusJournalParser.valensChoice"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValensChoice([NotNull] GladiusJournalParser.ValensChoiceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusJournalParser.journalTitle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJournalTitle([NotNull] GladiusJournalParser.JournalTitleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusJournalParser.journalTitle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJournalTitle([NotNull] GladiusJournalParser.JournalTitleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusJournalParser.journalText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJournalText([NotNull] GladiusJournalParser.JournalTextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusJournalParser.journalText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJournalText([NotNull] GladiusJournalParser.JournalTextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusJournalParser.shop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShop([NotNull] GladiusJournalParser.ShopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusJournalParser.shop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShop([NotNull] GladiusJournalParser.ShopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusJournalParser.gossip"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGossip([NotNull] GladiusJournalParser.GossipContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusJournalParser.gossip"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGossip([NotNull] GladiusJournalParser.GossipContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusJournalParser.minLevel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMinLevel([NotNull] GladiusJournalParser.MinLevelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusJournalParser.minLevel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMinLevel([NotNull] GladiusJournalParser.MinLevelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusJournalParser.quest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuest([NotNull] GladiusJournalParser.QuestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusJournalParser.quest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuest([NotNull] GladiusJournalParser.QuestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusJournalParser.prize"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrize([NotNull] GladiusJournalParser.PrizeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusJournalParser.prize"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrize([NotNull] GladiusJournalParser.PrizeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusJournalParser.success"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSuccess([NotNull] GladiusJournalParser.SuccessContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusJournalParser.success"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSuccess([NotNull] GladiusJournalParser.SuccessContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusJournalParser.failure"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFailure([NotNull] GladiusJournalParser.FailureContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusJournalParser.failure"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFailure([NotNull] GladiusJournalParser.FailureContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusJournalParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] GladiusJournalParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusJournalParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] GladiusJournalParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusJournalParser.encounter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEncounter([NotNull] GladiusJournalParser.EncounterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusJournalParser.encounter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEncounter([NotNull] GladiusJournalParser.EncounterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusJournalParser.onetime"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOnetime([NotNull] GladiusJournalParser.OnetimeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusJournalParser.onetime"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOnetime([NotNull] GladiusJournalParser.OnetimeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusJournalParser.lastDay"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLastDay([NotNull] GladiusJournalParser.LastDayContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusJournalParser.lastDay"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLastDay([NotNull] GladiusJournalParser.LastDayContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusJournalParser.relativeDay"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelativeDay([NotNull] GladiusJournalParser.RelativeDayContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusJournalParser.relativeDay"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelativeDay([NotNull] GladiusJournalParser.RelativeDayContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusJournalParser.item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterItem([NotNull] GladiusJournalParser.ItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusJournalParser.item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitItem([NotNull] GladiusJournalParser.ItemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusJournalParser.yank"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterYank([NotNull] GladiusJournalParser.YankContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusJournalParser.yank"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitYank([NotNull] GladiusJournalParser.YankContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GladiusJournalParser.location"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocation([NotNull] GladiusJournalParser.LocationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GladiusJournalParser.location"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocation([NotNull] GladiusJournalParser.LocationContext context);
}
